# Generated by Django 4.2.1 on 2023-10-03 19:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customusersb_about_me_customusersb_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
        migrations.AddField(
            model_name='customusersb',
            name='accept_politics',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=ckeditor.fields.RichTextField(default=None, null=True),
        ),
    ]
